<?php
/**
 * Plugin Name: Manacost Media Upload Accelerator
 * Description: Keeps essential image sizes synchronous and creates heavy sizes after the upload response.
 * Version: 1.0.0
 * Author: Manacost
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
	exit;
}

final class Manacost_Media_Upload_Accelerator
{
	private const HOOK = 'manacost_media_upload_accelerator_generate_subsizes';
	private const GROUP = 'manacost-media-upload-accelerator';
	private const MAX_ATTEMPTS = 3;
	private const DEFERRED_SIZES = ['1536x1536', '2048x2048'];

	/** @var array<int, int> */
	private static array $pending_attachments = [];

	public static function boot(): void
	{
		add_filter('intermediate_image_sizes_advanced', [__CLASS__, 'filter_sizes'], 10, 3);
		add_filter('wp_generate_attachment_metadata', [__CLASS__, 'queue_after_metadata'], 100, 3);
		add_action('shutdown', [__CLASS__, 'flush_pending_queue'], 30);
		add_action(self::HOOK, [__CLASS__, 'generate_deferred_subsizes'], 10, 2);
	}

	/**
	 * Leave essential sizes available to the editor immediately after upload.
	 * The two largest standard sizes are generated by the background worker.
	 *
	 * @param mixed $sizes
	 * @return mixed
	 */
	public static function filter_sizes($sizes, array $metadata = [], int $attachment_id = 0)
	{
		unset($metadata, $attachment_id);

		if (!self::is_upload_request() || !is_array($sizes)) {
			return $sizes;
		}

		foreach (self::DEFERRED_SIZES as $size_name) {
			unset($sizes[$size_name]);
		}

		return $sizes;
	}

	/**
	 * Queue missing large sizes after the initial metadata has been saved.
	 *
	 * @param mixed $metadata
	 * @return mixed
	 */
	public static function queue_after_metadata($metadata, int $attachment_id, string $context = 'create')
	{
		if (
			'create' !== $context
			|| !self::is_upload_request()
			|| !is_array($metadata)
			|| $attachment_id <= 0
			|| !function_exists('wp_attachment_is_image')
			|| !wp_attachment_is_image($attachment_id)
			|| !self::has_deferred_sizes_missing($metadata)
		) {
			return $metadata;
		}

		self::$pending_attachments[$attachment_id] = $attachment_id;

		return $metadata;
	}

	public static function flush_pending_queue(): void
	{
		$attachment_ids = self::$pending_attachments;
		self::$pending_attachments = [];

		foreach ($attachment_ids as $attachment_id) {
			self::enqueue($attachment_id, 0);
		}
	}

	public static function generate_deferred_subsizes(int $attachment_id, int $attempt = 0): void
	{
		if (
			$attachment_id <= 0
			|| !function_exists('wp_attachment_is_image')
			|| !wp_attachment_is_image($attachment_id)
			|| !function_exists('wp_update_image_subsizes')
		) {
			return;
		}

		try {
			$result = wp_update_image_subsizes($attachment_id);
		} catch (Throwable $error) {
			self::retryOrRecordError($attachment_id, $attempt, $error->getMessage());
			return;
		}

		if (is_wp_error($result)) {
			self::retryOrRecordError($attachment_id, $attempt, $result->get_error_message());
		}
	}

	private static function enqueue(int $attachment_id, int $attempt, int $delay = 0): void
	{
		$args = [$attachment_id, $attempt];

		if (function_exists('as_enqueue_async_action') && 0 === $delay) {
			// Action Scheduler uniqueness is scoped to hook and group in the DB
			// store, so it would collapse different attachment IDs in a burst.
			as_enqueue_async_action(self::HOOK, $args, self::GROUP, false);
			return;
		}

		if (function_exists('as_schedule_single_action')) {
			as_schedule_single_action(time() + $delay, self::HOOK, $args, self::GROUP, false);
			return;
		}

		if (!function_exists('wp_schedule_single_event')) {
			return;
		}

		if (0 === $delay && function_exists('wp_next_scheduled') && wp_next_scheduled(self::HOOK, $args)) {
			return;
		}

		wp_schedule_single_event(time() + max(1, $delay), self::HOOK, $args);
	}

	private static function retryOrRecordError(int $attachment_id, int $attempt, string $message): void
	{
		if ($attempt + 1 < self::MAX_ATTEMPTS) {
			self::enqueue($attachment_id, $attempt + 1, 60);
			return;
		}

		update_post_meta(
			$attachment_id,
			'_manacost_media_upload_accelerator_error',
			substr($message, 0, 500)
		);
	}

	private static function has_deferred_sizes_missing(array $metadata): bool
	{
		if (!function_exists('wp_get_registered_image_subsizes')) {
			return false;
		}

		$registered_sizes = wp_get_registered_image_subsizes();
		$generated_sizes = isset($metadata['sizes']) && is_array($metadata['sizes']) ? $metadata['sizes'] : [];

		foreach (self::DEFERRED_SIZES as $size_name) {
			if (isset($registered_sizes[$size_name]) && !isset($generated_sizes[$size_name])) {
				return true;
			}
		}

		return false;
	}

	private static function is_upload_request(): bool
	{
		$script_name = isset($_SERVER['SCRIPT_FILENAME']) ? basename((string) $_SERVER['SCRIPT_FILENAME']) : '';
		if ('async-upload.php' === $script_name) {
			return true;
		}

		if (!function_exists('wp_doing_ajax') || !wp_doing_ajax()) {
			return false;
		}

		$action = isset($_REQUEST['action']) && is_scalar($_REQUEST['action']) ? (string) $_REQUEST['action'] : '';

		return 'upload-attachment' === $action;
	}
}

Manacost_Media_Upload_Accelerator::boot();
